MONITORING_USER_SESSION
-----------------------

  CREATE TABLE "DB"."MONITORING_USER_SESSION" 
   (	"PROCESSED_DATE" DATE, 
	"PROCESSED_DATETIME" TIMESTAMP (6), 
	"USER_ROLE" VARCHAR2(256 BYTE), 
	"USER_SESSION_NUM" NUMBER, 
	"MESSAGE_EMAIL" VARCHAR2(256 BYTE), 
	"PARAM_IN_FLAG_MODE" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DB"   NO INMEMORY ;

   COMMENT ON COLUMN "DB"."MONITORING_USER_SESSION"."PROCESSED_DATE" IS 'Дата учета';
   COMMENT ON COLUMN "DB"."MONITORING_USER_SESSION"."PROCESSED_DATETIME" IS 'Дата+Время исполнения процедуры';
   COMMENT ON COLUMN "DB"."MONITORING_USER_SESSION"."USER_ROLE" IS 'Название роли пользователя';
   COMMENT ON COLUMN "DB"."MONITORING_USER_SESSION"."USER_SESSION_NUM" IS 'Общее количество созданных сессий пользователей за сутки для соответствующей роли';
   COMMENT ON COLUMN "DB"."MONITORING_USER_SESSION"."MESSAGE_EMAIL" IS 'Кому отправлять сообщения';
   COMMENT ON COLUMN "DB"."MONITORING_USER_SESSION"."PARAM_IN_FLAG_MODE" IS 'Параметр режима запуска - технический параметр (WORK|TEST)';

